=== Silver1441/XML_JSON_parsers/src/main/resources/xml/product_list.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="product_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subcategory" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="article" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="manufacturer" type="xs:string"/>
                                                    <xs:element name="model">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[a-zA-Z][a-zA-Z][0-9][0-9][0-9]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="production_date">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[0-9][0-9][-][0-9][0-9][-][0-9][0-9][0-9][0-9]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="color" type="xs:string"/>
                                                    <xs:element name="price" type="xs:double"/>
                                                </xs:sequence>
                                                <xs:attribute name = "id" type="xs:long" use="required"/>
                                                <xs:attribute name = "stock" type="xs:int" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name = "id" type="xs:long" use="required"/>
                                    <xs:attribute name = "name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name = "id" type="xs:long" use="required"/>
                        <xs:attribute name = "name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Silver1441/XML_JSON_parsers/src/main/resources/xml/mock_product_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<product_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="product_list.xsd">
    <category name = "devices">
        <subcategory name = "smartphones">
            <article id ="100101" stock = "12">
                <manufacturer>Samsung</manufacturer>
                <model>GX106</model>
                <production_date>12-01-2019</production_date>
                <color>black</color>
                <price>24499</price>
            </article>

            <article id ="100102" stock = "4">
                <manufacturer>LG</manufacturer>
                <model>NN805</model>
                <production_date>18-11-2018</production_date>
                <color>pink</color>
                <price>31999</price>
            </article>
        </subcategory>

        <subcategory name = "tablets">
            <article id ="100201" stock = "2">
                <manufacturer>Xiaomi</manufacturer>
                <model>AN001</model>
                <production_date>22-04-2018</production_date>
                <color>gold</color>
                <price>18999</price>
            </article>

            <article id ="100202" stock = "0">
                <manufacturer>ASUS</manufacturer>
                <model>AG509</model>
                <production_date>18-11-2018</production_date>
                <color>white</color>
                <price>41999</price>
            </article>
        </subcategory>
    </category>

    <category name = "accessories">
        <subcategory name = "cases">
            <article id ="200101" stock = "12">
                <manufacturer>Super cases</manufacturer>
                <model>CB023</model>
                <production_date>18-03-2016</production_date>
                <color>black</color>
                <price>1199</price>
            </article>

            <article id ="200202" stock = "6">
                <manufacturer>Pela</manufacturer>
                <model>ES909</model>
                <production_date>05-05-2019</production_date>
                <color>transparent</color>
                <price>1799</price>
            </article>
        </subcategory>
    </category>
</product_list>
